### ISSUE TITLE
Doesn't work. No logs.

### ISSUE THREAD

**Issue by vladislav-tkach** [M6D6M6A/G_MODE#1]
Hi!

Thank you for the utility! It looks great.
Unfortunately, it doesn't work for me.
I also don't see any logs to try to diagnose the issue. So I propose adding some logging to the script.

**Comment by M6D6M6A** [comment]
Hey, sure i will implement logging, when i have time, did you run it as admin? :)

**Comment by vladislav-tkach** [comment]
I tried both: if the script is run without admin rights, it asks for them in order to execute the powershell script, but nothing happens afterwards; and if the script is run with the admin rights, it seems like nothing happens at all.

This is all I get if I the script is launched via `cscript`:
`Microsoft (R) Windows Script Host Version 5.812`
`Copyright (C) Microsoft Corporation. All rights reserved.`

**Comment by M6D6M6A** [comment]
I would recomend to run the manager, i have added logging using GTP since i have no time today, i hope it creates the log file ;)

**Comment by vladislav-tkach** [comment]
Thank you.

Apparently the issue was on my side. It is required to configure the execution policy in Windows to run unsigned scripts, which I didn't know. I suggest adding this to your usage guide.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

The VB scripts still do not work for me :(. Although the powershell scripts do, so it's enough for me. Again, thank you for the tool.

By the way, the log file isn't created and I'm not sure the changes you've made to the code left the main functionality unchanged

**Comment by M6D6M6A** [comment]
Ty for sharing your solution, i will add this to the readme, when i have more time :)

**Comment by M6D6M6A** [comment]
I just improved the manager logic and reworked the logging text. I want to add some sort of debug and production logging and settings later, but for now it is already much cleaner OOP code than before. Not sure if you saw it, but I also added a proper fix to be able to run the scripts after downloading them a few months ago.

**Comment by M6D6M6A** [comment]
I just improved the manager logic and reworked the logging text. I want to add some sort of debug and production logging and settings later, but for now it is already much cleaner OOP code than before. Not sure if you saw it, but I also added a proper fix to be able to run the scripts after downloading them a few months ago.
